################################################################################
# training parameters
################################################################################
train:
  # loss: "xentropy"       # must be either xentropy or iou
  loss: "focal_gamma"
  max_epochs: 100
  lr: 0.005               # sgd learning rate
  min_lr: 2.0e-5
  wup_epochs: 3         # warmup during first XX epochs (can be float)
  cos_epochs: 92
  momentum: 0.9          # sgd momentum
  lr_decay: 0.9        # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.01        # weight decay
  batch_size: 12         # batch size
  report_batch: 200       # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.01       # class weight w = 1 / (content + epsilon_w)
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  workers: 4           # number of threads to get data

################################################################################
# backbone parameters
################################################################################
model:
  name: "JunNet13"  
  in_channels: 5
  dropout: 0.3
  bn_d: 0.01
  use_mps: False

################################################################################
# postproc parameters
################################################################################
post:
  KNN:
    use: True
    params:
      knn: 5
      search: 5
      sigma: 1.0 
      cutoff: 1.0

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "SemanticKitti"
  scans: "SemanticKitti"
  # max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    # fov_up: 3
    # fov_down: -25 
    img_prop:
      # width: 512
      width: 2048
      height: 64
    img_means: #range,x,y,z,signal
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds: #range,x,y,z,signal
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16

    fov_up: 3
    fov_down: -23
  max_points: 130000 # max of any scan in dataset
